### ISSUE TITLE
No results at some organisation 

### ISSUE THREAD

**Issue by rienJa** [carambolecomputer/issue-tracker#2]
After selecting  'KNBB district Nijmegen' competition 'Driebanden B2'  table 'KNBB district Nijmegen/ Driebanden B2' the results are empty.

**Comment by rvgate** [comment]
Thank you for using the tool and many more thanks for reporting!

It actually applied to all competitions that had an extra division of poules underneath.
I have just deployed a new version that fixes this bug.

Go check it out: https://www.carambolecomputer.nl/players-export
